import type { Metadata } from "next";
import { Noto_Sans_KR, Pacifico, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const notoSansKr = Noto_Sans_KR({ 
  subsets: ["latin"], 
  weight: ["400", "500", "700"],
  variable: "--font-noto"
});

const pacifico = Pacifico({ 
  subsets: ["latin"], 
  weight: ["400"],
  variable: "--font-pacifico"
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSansKr.variable} ${pacifico.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
